### ISSUE TITLE
dataframe insert

### ISSUE THREAD

**Issue by venkatgogineni** [JuliaDatabases/MySQL.jl#169]
When I conducted a benchmark (without database inserts) between python, julia and java, I found julia performing the same tasks at 1/10th time against python and a shade better than java. When I include database inserts, julia is performing poorly.
Iterating through a dataframe and inserting in MySQL database is consuming lot of time
Below code runs in a loop, deriving  values from the dataframe
q = "INSERT INTO stocks.quandl (field1, field2,field3,,field4,date) VALUES ("
cama = ',' 
insert_statement = string(q, "'", fld1, "'",cama,fld2,cama,fld3,cama,fld4,cama,"'",dt,"')")
stmt = DBInterface.prepare(conn, insert_statement )
DBInterface.execute(stmt) 
field1 and date is key. Can I optimize the code further. Is there anything similar to df.to_sql

**Comment by quinnj** [comment]
Hi @venkatgogineni , sorry for the slow response. You can use the `MySQL.load(df, conn, dt)` function to efficiently load all rows from a DataFrame into a table with name `dt`. If you'd rather use your own insert statement, you should probably wrap each execute like:
```julia
MySQL.transaction(conn) do
    for row in eachrow(df)
        DBInterface.execute(stmt, row)
    end
end
```
Wrapping each execute in the `transaction` block will ensure only one commit will happen at the end instead of after every execute.
