### ISSUE TITLE
Dates parsing failure

### ISSUE THREAD

**Issue by linusheinz** [JuliaDatabases/MySQL.jl#188]
Hey nice project 

I am querying a table with a timestamp:
```
data = DBInterface.execute(database, sql)
df = DataFrame(data)

```

But I get :
```
ERROR: LoadError: error parsing DateTime from "2022-01-04 15:08:44.171540"
```
The corresponding stacktrace:

```
 [1] error(s::String)
    @ Base .\error.jl:33
  [2] casterror(T::Type, ptr::Ptr{UInt8}, len::UInt32)
    @ MySQL C:\Users\lheinz\.julia\packages\MySQL\0vHyV\src\execute.jl:53
  [3] cast(#unused#::Type{DateTime}, ptr::Ptr{UInt8}, len::UInt32)       
    @ MySQL C:\Users\lheinz\.julia\packages\MySQL\0vHyV\src\execute.jl:76
  [4] cast
    @ C:\Users\lheinz\.julia\packages\MySQL\0vHyV\src\execute.jl:32 [inlined]
  [5] getcolumn
    @ C:\Users\lheinz\.julia\packages\MySQL\0vHyV\src\execute.jl:100 [inlined]
  [6] eachcolumns
    @ C:\Users\lheinz\.julia\packages\Tables\PxO1m\src\utils.jl:111 [inlined]
  [7] buildcolumns(schema::Tables.Schema{(:Columnames), Tuple{String, Union{Missing, String}, Union{Missing, String}, Union{Missing, String}, Union{Missing, String}, Union{Missing, String}, Union{Missing, String}, Union{Missing, String}, Union{Missing, String}, Union{Missing, DateTime}}}, rowitr::MySQL.TextCursor{true})
    @ Tables C:\Users\lheinz\.julia\packages\Tables\PxO1m\src\fallbacks.jl:135
  [8] columns
    @ C:\Users\lheinz\.julia\packages\Tables\PxO1m\src\fallbacks.jl:251 [inlined]
  [9] DataFrame(x::MySQL.TextCursor{true}; copycols::Nothing)
    @ DataFrames C:\Users\lheinz\.julia\packages\DataFrames\MA4YO\src\other\tables.jl:58
 [10] DataFrame(x::MySQL.TextCursor{true})
    @ DataFrames C:\Users\lheinz\.julia\packages\DataFrames\MA4YO\src\other\tables.jl:49
 [11] top-level scope
    @ c:\Users\lheinz\FlowDashboard.jl\test.jl:40
in expression starting at c:\Users\lheinz\FlowDashboard.jl\test.jl:40
```

I posted it in the forum and got some help 👍 

https://discourse.julialang.org/t/parsing-of-mysql-timestamps/77587/3

**Comment by quinnj** [comment]
Hi @linusheinz! Sorry for the slow review here; I've been pretty backed up w/ things lately and am trying to catch up.

My guess is that we're running into an error here because of Julia's limited precision with the `DateTime` type. It only handles up to millisecond precision and it looks like that timestamp has `540` microseconds in addition, so it's getting tripped up.

I have a few thoughts on this, ranging from easier to harder. I actually wrote the original `Dates` stdlib for Julia and have some ideas on extending it further to support up to nanosecond precision, but that's a pretty heavy change that would take time to percolate to publicly released Julia. On the other hand, we could perhaps give a way to at least "truncate and warn" while trying to read this kind of timestamps. Alternatively, we could maybe provide a sort of "shim" struct that was something like:
```julia
struct DateAndTime
    date::Date
    time::Time
end
```
since the `Time` type already has nanosecond precision and this would give us full compatibility. I think this is probably my preference and then try to make it act as much like a `DateTime` as possible with all the operations defined.

**Comment by quinnj** [comment]
Fixed in https://github.com/JuliaDatabases/MySQL.jl/pull/178
