### ISSUE TITLE
ccall fails when trying to use mysql_init from mysql_lib

### ISSUE THREAD

**Issue by SamMcConnell** [JuliaDatabases/MySQL.jl#97]
I was wondering if this might have to do with the config.jl file being deleted between the 227th and 228th commits.  Was that intentional?  

If it was intentional, how would you go about getting mysql_init to a place where it can be found by ccall?  I was under the impression that there might be a MySQL.so file I'd need to move or provide the path to somewhere if that were the case.

Any help is greatly appreciated!  Sorry if I'm misunderstanding anything!

Edit:
Adding an example of an error message...
```
    julia> MySQL.connect("<host>", "<user>", "<password>")
    ERROR: ccall: could not find function mysql_init in library
    Stacktrace:
      [1] #connect#8(::String, ::Int64, ::String, ::UInt32, ::Dict{Any,Any}, ::Function, ::String, ::String, ::String) at /home/Sam/.julia/v0.6/MySQL/src/MySQL.jl:45
      [2] connect(::String, ::String, ::String) at /home/Sam/.julia/v0.6/MySQL/src/MySQL.jl:44
```

**Comment by quinnj** [comment]
This is the current logic that was copied over from the config.jl file
```julia
let
    global mysql_lib
    if !isdefined(@__MODULE__, :mysql_lib)
        @static Compat.Sys.islinux()   && (lib_choices = ["libmysql.so", "libmysqlclient.so", "libmysqlclient_r.so", "libmariadb.so", "libmysqlclient_r.so.16"])
        @static Compat.Sys.isapple()   && (lib_choices = ["libmysqlclient.dylib", "libperconaserverclient.dylib"])
        @static Compat.Sys.iswindows() && (lib_choices = ["libmysql.dll", "libmariadb.dll"])
        lib = Libdl.find_library(lib_choices)
        const mysql_lib = lib
    end
end
```
Basically, we try a bunch of different options on the various platforms to try and find the shared library file.

What OS are you running on? Can you snoop around `/usr/local/lib` and try to find what your `.so` file is called?

**Comment by SamMcConnell** [comment]
I'm running it off of Bash on Ubuntu on Windows.  I found this file, could it be the one?
libmysqlclient.so.18.0.0

**Comment by quinnj** [comment]
ok, just pushed an update. can you run:
```julia
Pkg.checkout("MySQL")
using MySQL
MySQL.API.mysql_lib
```
and see if that works?

**Comment by jvkerckh** [comment]
I have the exact same issue as @SamMcConnell, running from Atom on Ubuntu.

I've tried the fix that @quinnj suggested but it did not do the trick.

**Comment by piever** [comment]
I also have the same issue and it is not fixed by the @quinnj suggestion.

**Comment by quinnj** [comment]
Hey all, sorry for the delay in responding here; it took a bit, but I've finally managed to get an integration w/ BinaryBuilder.jl/BinaryProvider.jl packages working so that the necessary shared library is downloaded/used automatically w/o any need for configuring by the user. In short, when somebody does `Pkg.add("MySQL")`, it will make sure they have the necessary C code automatically. It should also simplify any versioning issues, because we can ensure from the MySQL.jl package that we're always using the same library.

Anyway, I'm going to tag a new release so that the new updates are available for everyone; let me know if anyone sees any issues upgrading.

**Comment by quinnj** [comment]
PR reference: #100
